name = "xkcd"
account_id = ""
route = "someroute.com/*"
workers_dev = true
main = "./dist/index.js"

usage_model = "unbound"
compatibility_date = "2022-05-11"

kv_namespaces = [
    {binding = "DATA", id = "", preview_id = ""}
]

[triggers]
crons = ["* * * * *"]

[build]
command = "npm run build"

[site]
bucket = "./static"